### ISSUE TITLE
Crash reporter no longer has a working sink

### ISSUE THREAD

**Issue by davidewatson** [samsung-cnct/k2-crash-application#20]
Due to recent DNS changes, the crash reporter no longer points to a valid CNAME. There may be other problems too.

> [CRASHAPP] Error sending POST request: Post https://k2crashreporter.kubeme.io/k2crashreporter/k2crashes: dial tcp: lookup k2crashreporter.kubeme.io on 10.96.0.10:53: no such host

```
rodin:zabra dwat$ nslookup k2crashreporter.kubeme.io
Server:		192.168.1.1
Address:	192.168.1.1#53

** server can't find k2crashreporter.kubeme.io: NXDOMAIN

rodin:zabra dwat$ 
```

**Comment by coffeepac** [comment]
my bad.  one moment.

**Comment by coffeepac** [comment]
recreated the record (I didn't think any old copies of the crash app were still being used.  my bad!)

give it five minutes (so 10:55) and try again.

**Comment by davidewatson** [comment]
Works again!
