### ISSUE TITLE
Kibana for MVP

### ISSUE THREAD

**Issue by leahnp** [samsung-cnct/k2-crash-application#5]
Debug kibana in the production cluster, get crashes displaying.
Create data viz for crashes over time and top tasks that fail.

**Comment by leahnp** [comment]
ElasticSearch cluster appears to be in good health: 

`$ /_cat/health`
`1501777526 16:25:26 elasticsearch-cluster green 6 3 111 54 0 0 0 0 - 100.0%`

**Comment by leahnp** [comment]
Kibana logs that are concerning, but not precise or verbose:

```{"type":"log","@timestamp":"2017-04-06T06:40:01Z","tags":["status","ui settings","error"],"pid":11,"state":"red","message":"Status changed from green to red - Elasticsearch plugin is red","prevState":"green","prevMsg":"Ready"}```

**Comment by leahnp** [comment]
Kibana Image: kibana:5.0.2
Kibana Version: /# kibana version 5.0.2


ES Image: custom
ES Version: 5.0.0
```
#  curl -XGET 'localhost:9200'
{
  "name" : "elasticsearch-data-0",
  "cluster_name" : "elasticsearch-cluster",
  "cluster_uuid" : "h72TJQ2CTn-2yRYXVB9puA",
  "version" : {
    "number" : "5.0.0",
    "build_hash" : "253032b",
    "build_date" : "2016-10-26T05:11:34.737Z",
    "build_snapshot" : false,
    "lucene_version" : "6.2.0"
  },
  "tagline" : "You Know, for Search"
}
```

**Comment by leahnp** [comment]
Can ping ES from Kibana pod:
```
# ping elasticsearch       
PING elasticsearch.kube-system.svc.cluster.local (10.128.64.2): 56 data bytes
64 bytes from 10.128.64.2: icmp_seq=0 ttl=62 time=0.878 ms
64 bytes from 10.128.64.2: icmp_seq=1 ttl=62 time=0.396 ms
64 bytes from 10.128.64.2: icmp_seq=2 ttl=62 time=0.459 ms
64 bytes from 10.128.64.2: icmp_seq=3 ttl=62 time=0.381 ms
64 bytes from 10.128.64.2: icmp_seq=4 ttl=62 time=0.468 ms
64 bytes from 10.128.64.2: icmp_seq=5 ttl=62 time=0.447 ms
64 bytes from 10.128.64.2: icmp_seq=6 ttl=62 time=0.437 ms
64 bytes from 10.128.64.2: icmp_seq=7 ttl=62 time=0.896 ms
^C--- elasticsearch.kube-system.svc.cluster.local ping statistics ---
8 packets transmitted, 8 packets received, 0% packet loss
```

**Comment by leahnp** [comment]
Tried restarting Kibana, no change

**Comment by coffeepac** [comment]
possible underlying issue:  https://github.com/samsung-cnct/issues/issues/18

**Comment by leahnp** [comment]
I think I need to update the elasticsearch version to 5.0.2 from following log:

```
{"version":"5.0.0","http":{"publish_address":"10.128.40.4:9200"},"ip":"10.128.40.4"}],"message":"You're running Kibana 5.0.2 with some different versions of Elasticsearch. Update Kibana or Elasticsearch to the same version to prevent compatibility issues: v5.0.0 @ 10.128.196.5:9200 (10.128.196.5), v5.0.0 @ 10.128.64.2:9200 (10.128.64.2), v5.0.0 @ 10.128.80.4:9200 (10.128.80.4), v5.
```

Problems: elasticsearch was installed via central-logging helm chart. Since it was deployed there have been several untested changes to charts inside central-logging. Also, elasticsearch image in config file does not seem to reflect the deployment...the es quay repo indicated that the latest build failed.

**Comment by leahnp** [comment]
Updated the es quay repo to build from github push to ensure we know the latest build reflects what is in our es github repo. https://quay.io/repository/samsung_cnct/elasticsearch?tab=builds

**Comment by leahnp** [comment]
Updated central-logging helm chart - es updated kibana version did not.

**Comment by leahnp** [comment]
Trying to add full link to image.... https://github.com/samsung-cnct/k2-charts/pull/121

**Comment by leahnp** [comment]
Now running into issue already documented by user: https://github.com/samsung-cnct/k2-charts/issues/118

**Comment by leahnp** [comment]
Success on dep update:

```
$ helm dependency update
Hang tight while we grab the latest from your chart repositories...
...Unable to get an update from the "local" chart repository (http://127.0.0.1:8879/charts):
	Get http://127.0.0.1:8879/charts/index.yaml: dial tcp 127.0.0.1:8879: getsockopt: connection refused
...Successfully got an update from the "stable" chart repository
...Successfully got an update from the "cnct" chart repository
Update Complete. ⎈Happy Helming!⎈
Saving 5 charts
Downloading daemon-fluentd from repo http://atlas.cnct.io
Downloading kafka from repo http://atlas.cnct.io
Downloading central-fluentd from repo http://atlas.cnct.io
Downloading elasticsearch from repo http://atlas.cnct.io
Downloading kibana from repo http://atlas.cnct.io
```

**Comment by leahnp** [comment]
New issue: 

```
$  helm upgrade central-logging cnct/central-logging
Error: UPGRADE FAILED: error validating "": error validating data: found invalid field tolerations for v1.PodSpec
```

https://github.com/fluent/fluentd-kubernetes-daemonset/issues/38

**Comment by leahnp** [comment]
Confused about line #106: https://github.com/samsung-cnct/k2-charts/blob/master/daemon-fluentd/templates/fluentd.yaml

Currently: `{{ .Values.scheduling.affinity.node.type }}:`
But I feel like it should be: `type: {{ .Values.scheduling.affinity.node.type }}`

**Comment by leahnp** [comment]
I think our problem is line #126 or #124 https://github.com/samsung-cnct/k2-charts/blob/master/daemon-fluentd/templates/fluentd.yaml

**Comment by leahnp** [comment]
Had to add new namespace to prod cluster:
```
$ kubectl create -f namespace.json 
namespace "kube-logging" created
```

**Comment by leahnp** [comment]
Hurray!!! Chart upgraded:
```
$ helm list
NAME               	REVISION	UPDATED                 	STATUS  	CHART                   	NAMESPACE          
central-logging    	3       	Fri Aug  4 14:18:56 2017	DEPLOYED	central-logging-0.2.2   	kube-system 
```

**Comment by leahnp** [comment]
**Status:** 

By updating the central-logging chart, some charts got installed in kube-logging namespace - but the corresponding old charts in kube-system did not get removed. (so there are fluentd daemons running in both kube-logging and kube-system now...)

Elasticsearch master nodes got updated to version 5.4.2 BUT Elasticseach data nodes are still at 5.0.0 - it's unclear why this is since they are both using the same image. 

Moving forward I think I should first, get all the logging resources running in kube-logging namespace THEN delete the resources running in kube-system.  Then deal with why the elasticsearch version in data nodes will not update.

The token and login url for the prod cluster has stopped working for me....unsure if that is related to my work today.  How can I verify the webserver is running (it doesn't seem to be).

**Comment by leahnp** [comment]
Deleted the whole logging system

**Comment by leahnp** [comment]
Had to add new namespaces to es host: https://github.com/samsung-cnct/k2-charts/pull/130

Redeployed central-logging chart, this will have to be addressed with the upcoming logging work (out of scope).

Current status 3 hours after deployment:

- `default               zk-0                                                         0/1       Init:0/2            0          2h`
- no zk-1, zk-2
- `default               kafka-monitor-3478443908-b1q0z                               0/1       CrashLoopBackOff    34         2h`
- `default               kafka-0                                                      0/1       ImagePullBackOff    0          2h`
- no kafka-1, kafka-2
- All fluentd: `kube-logging          fluentd-daemon-10wls                                         1/2       CrashLoopBackOff    35         2h`

**Comment by leahnp** [comment]
Pushed changes necessary, but atlas is not updating. Both central-logging and atlas not updating current chart version.

**Comment by leahnp** [comment]
Elasticsearch/ingress working properly.
Kibana endpoint hitting `ERR_TOO_MANY_REDIRECTS` I think it's related to the change in es namespace, pr submitted to fix.

**Comment by leahnp** [comment]
Now I am seeing: ` "Status changed from yellow to red - X-Pack plugin is not installed on Elasticsearch cluster"` from kibana logs that seems to be related to: https://github.com/elastic/kibana-docker/issues/27#issuecomment-296524205

Need to pass flags to es and kibana to get them working together.

**Comment by leahnp** [comment]
<img width="1173" alt="screen shot 2017-08-10 at 7 43 00 pm" src="https://user-images.githubusercontent.com/13352646/29196711-36558538-7e04-11e7-949c-d61fdf62be2a.png">
logs.

**Comment by leahnp** [comment]
TO review: get the kibana url from me (ping me in slack) go to Kibana, select k2crashreporter index, see logs. Logs are huge, takes a while to load, you might have to tweak discover:sampleSize to less than 500 for quick response.

**Comment by guineveresaenger** [comment]
I can see logs! Looks like it works to me.
