### ISSUE TITLE
Write server side app to monitor http requests

### ISSUE THREAD

**Issue by leahnp** [samsung-cnct/k2-crash-application#6]
App to check requests to elasticsearch cluster are as expected (not malicious).

**Comment by oneilcin** [comment]
@coffeepac From our brief discussion, this will be a long running application that receives HTTP requests from the k2 crash application and then forwards validated requests to elastic search.  Can you clarify the TLS flow?  Would the crash app be sending over secure HTTPS to the this new 'http monitor application'?  Would the 'http monitor application' send over secure HTTPS to elastic search?

**Comment by oneilcin** [comment]
Design Proposal:

The k2-crash-app is installed in k2-tools and can run on a client's laptop.
The new backend-monitor-app along with Elastic Search will be deployed within our k2 cluster (k2-crash-app is used in the Production cluster now).
We will need to use an ingress controller (nginx) to accept HTTPS connections from the k2-crash-app.  The request can be forwarded as http to the new backend-monitor-app.  The new backend-monitor-app can then forward validated requests to elasticsearch over http.
The new backend-monitor-app could be used to check requests from other services in the future.  The new backend-monitor-app will reside in a Deployment
Investigation Needed:
1. Determine what designates a valid elasticsearch request from the k2-crash-app.
2. Learn how this is used in our Production cluster (how to access, etc)
3. Create a new cert with Lets Encrypt (learn how to setup)
4. Learn how to setup the Ingress to terminate SSL at the controller and forward the request to my backend app.

**Comment by coffeepac** [comment]
this looks good as a design!  To help with 3 & 4 here is a snippet that should Just Work in the production cluster (no need for you to thrash around sorting out something that's already installed):

```apiVersion:
extensions/v1beta1
kind: Ingress
metadata:
  name: <name of ingress object, k2-crash-backend-ingress or whatever>
  namespace: <namespace of ingress>
  annotations:
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: "nginx"
spec:
  tls:
  - hosts:
    - <external DNS entry that we want to resolve to this application>
    secretName: <unique secret name>
  rules:
  - host: <external DNS entry that we want to resolve to this application>
    http:
      paths:
      - path: /
        backend:
          serviceName: <name of service that points to the k2-crash-backend deployment>
          servicePort: <port to resolve to, probably 80>```

**Comment by oneilcin** [comment]
Nice!  Does the tls.secretName hold the Cert?  Is there already a cert I can use in the production cluster?

**Comment by coffeepac** [comment]
interesting question!  maybe!  this is a bit of a black box to me.  I got it working and then ran off to do something else.

All I had to do was make sure the values for serviceName and servicePort referred to the service I wanted exposed via the ingress rule and it worked.

**Comment by oneilcin** [comment]
PR submitted:https://github.com/samsung-cnct/crash-app-backend/pull/2

**Comment by oneilcin** [comment]
Installed this in the common-tools production cluster
